/**
 * The interface's LegalManager ABI fragment, GENERATED from the same forge artifacts as everything
 * else (design §8, audit H4).
 *
 * The guardian veto card decodes `AmendmentScheduled` logs and calls
 * `cancelOperatingAgreementUpdate` with an ABI that lives in the interface package — because the
 * card must read the chain itself rather than trust a hash this backend handed it. That fragment
 * used to be typed by hand and defended by a 145-line drift test that re-parsed the TypeScript
 * literal out of the file with regexes.
 *
 * A guard that can only DETECT drift is the wrong shape when the source of truth is right here:
 * the copy is derived, so derive it. The generator emits the fragment, a freshness test
 * regenerates and diffs, and a contract change that alters one of these signatures now fails CI
 * with "run npm run gen:abis" rather than with an assertion about a regex.
 *
 * It stays a FRAGMENT rather than the whole 50-entry ABI, and the allowlist below is why: the
 * point of a small fragment is that a human has read every line of it, and nobody re-reads a
 * 50-entry paste. Adding a name here is a deliberate act.
 */

/** The five reads/writes and four events the guardian veto card cannot work without. */
export const LEGAL_MANAGER_FRAGMENT_MEMBERS = [
  "scheduledAt",
  "vetoed",
  "cancelOperatingAgreementUpdate",
  "liftVeto",
  "meta",
  "AmendmentScheduled",
  "AmendmentVetoed",
  "VetoLifted",
  "OperatingAgreementUpdated",
] as const;

type AbiParam = { name?: string; type: string; indexed?: boolean; internalType?: string };
type AbiEntry = {
  type: string;
  name?: string;
  inputs?: AbiParam[];
  outputs?: AbiParam[];
  stateMutability?: string;
  anonymous?: boolean;
};

const HEADER = `// GENERATED by back/backend/scripts/gen-abis.mts — do not edit by hand.
// Re-run \`npm run gen:abis\` in back/backend after \`forge build\`; a backend test
// (\`test/api/legalManagerAbiFragment.test.ts\`) fails CI when this file is stale.

/**
 * LegalManager ABI fragment — the guardian's OWN view of a pending amendment.
 *
 * It exists for a reason the design states plainly: the guardian veto card must read the chain
 * itself. If the card vetoed a hash the backend handed it, a compromised backend could choose what
 * gets vetoed — offer up a harmless hash, keep the malicious one scheduled, and the guardian's veto
 * would land on nothing (audit H4). So the card enumerates \`AmendmentScheduled\` from the entity's
 * own proxy over the user's own RPC, and this is the fragment it decodes with.
 *
 * Kept minimal on purpose: five reads/writes and four events, not the whole contract. The members
 * are an explicit allowlist in \`back/backend/src/abis/interfaceFragment.ts\`.
 *
 * Note the shape of veto on this contract: \`cancelOperatingAgreementUpdate\` DELETES \`scheduledAt\`
 * and sets \`vetoed\`, so a vetoed amendment reads back as \`scheduledAt == 0\` — "live" is
 * \`scheduledAt != 0\`, and \`vetoed\` is a separate, sticky flag that parks the hash until
 * \`liftVeto\`.
 */`;

/** Everything that changes CALLDATA or DECODING, and nothing that doesn't. */
function slimParam(p: AbiParam): AbiParam {
  return {
    name: p.name ?? "",
    type: p.type,
    ...(p.indexed === undefined ? {} : { indexed: p.indexed }),
  };
}

function slimEntry(entry: AbiEntry): AbiEntry {
  return {
    type: entry.type,
    ...(entry.name === undefined ? {} : { name: entry.name }),
    ...(entry.stateMutability === undefined ? {} : { stateMutability: entry.stateMutability }),
    inputs: (entry.inputs ?? []).map(slimParam),
    ...(entry.type === "event" ? {} : { outputs: (entry.outputs ?? []).map(slimParam) }),
  };
}

/**
 * Render the fragment module from a full LegalManager ABI.
 *
 * Ordered by the ALLOWLIST rather than by the artifact, so the output is a pure function of this
 * file plus the contract — a re-ordering inside `forge build` cannot produce a spurious diff. A
 * missing member throws: a fragment silently short of `scheduledAt` is a card that cannot tell a
 * live amendment from an executed one.
 */
export function renderLegalManagerFragment(abi: readonly unknown[]): string {
  const byName = new Map<string, AbiEntry>();
  for (const raw of abi) {
    const entry = raw as AbiEntry;
    if (entry.name) byName.set(entry.name, entry);
  }

  const entries = LEGAL_MANAGER_FRAGMENT_MEMBERS.map((name) => {
    const entry = byName.get(name);
    if (!entry) {
      throw new Error(
        `LegalManager ABI has no \`${name}\` — the interface fragment allowlist names it. Either the contract changed or the allowlist is stale.`,
      );
    }
    return slimEntry(entry);
  });

  return `${HEADER}\nexport const legalManagerAbi = ${JSON.stringify(entries, null, 2)} as const;\n`;
}
