/**
 * ⚠ GENERATED FILE — DO NOT EDIT. Regenerate with:
 *
 *     DOOLA_API_KEY=dk_test_… npx tsx scripts/refresh-naics.mts
 *
 * DATA ONLY, deliberately. Everything that READS this list — the membership check, the capped
 * renderer, and the prose explaining why the list is a build-time constant at all — lives in the
 * hand-written `naicsLabels.ts` beside it, which imports this. Keeping them apart means a
 * refresh is a diff of the array and nothing else: a generator that also emits behaviour is a
 * generator that silently reverts a fix to that behaviour the next time somebody runs it, and the
 * reviewer of the refresh PR has to re-read a hundred lines of unchanged prose to notice.
 *
 * Generated 2026-09-07 from the sandbox reference table: 821 labels.
 */

/** Every label the create-company endpoint accepts, exactly as doola spells it. */
export const NAICS_LABELS: readonly string[] = [
  "3D printing",
  "Accessories",
  "Accounting",
  "Acupuncture",
  "Admin support",
  "Adult entertainment",
  "Advertising",
  "Advertising consulting",
  "Aerial photography",
  "Aerospace engineering",
  "Aesthetics",
  "Affiliate marketing",
  "Agriculture",
  "Airbnb rentals",
  "Airplane charter",
  "Amazon business",
  "Amazon FBA",
  "Amusement park",
  "Anesthesia services",
  "Animal farming",
  "Antiques",
  "Apparel",
  "Apparel manufacturing",
  "Appliance repair",
  "Applied behavior analysis",
  "Aquaculture",
  "Aquatic plants farming",
  "Arborist",
  "Architecture",
  "Art",
  "Art and design",
  "Art gallery",
  "Artificial intelligence",
  "Artist",
  "Arts and crafts",
  "Asset management",
  "Assisted living",
  "Athletics",
  "ATM business",
  "Attorney",
  "Auctioneering",
  "Audiology",
  "Author",
  "Auto detailing",
  "Auto glass",
  "Auto repair",
  "Auto sales",
  "Automation",
  "Automotive customization",
  "Aviation",
  "Aviation maintenance",
  "Aviation school",
  "Aviation services",
  "Babysitting",
  "Baked goods",
  "Bakery",
  "Baking",
  "Band",
  "Bar",
  "Barber",
  "Barber examiner",
  "Barbershop",
  "Bartender",
  "Basketball training",
  "Beauty products",
  "Beauty salon",
  "Beauty services",
  "Bed and breakfast",
  "Behavioral health",
  "Behavioral science",
  "Beverage manufacturing",
  "Biotechnology",
  "Bitcoin mining",
  "Blogging",
  "Boat charter",
  "Boat rental",
  "Boat repair and maintenance",
  "Boat sales",
  "Body contouring",
  "Body sculpting",
  "Book publishing",
  "Bookkeeping",
  "Bookstore",
  "Brand services",
  "Brewery",
  "Broadcasting",
  "Building contracting company",
  "Building equipment contracting",
  "Building homes",
  "Business consulting",
  "Business development consulting",
  "Business management and operations",
  "Business strategy company",
  "Buy and sell real estate",
  "Cafe",
  "Call center",
  "Campground",
  "Candle making",
  "Candle store",
  "Candy",
  "Cannabis",
  "Car detailing",
  "Car detailing supplies",
  "Car garage",
  "Car leasing",
  "Car parts",
  "Car rental and leasing",
  "Car repair",
  "Car sales",
  "Car wash",
  "Cargo transportation in trucks",
  "Carpentry",
  "Carpet and upholstery cleaning",
  "Carpet cleaning",
  "Casino hotel",
  "Catering",
  "Cattle ranching",
  "CBD dispensary",
  "Cell phone store",
  "Ceramics",
  "Charity",
  "Child daycare",
  "Childcare services",
  "Children's clothing",
  "Chiropractors",
  "Church",
  "Civil engineering",
  "Cleaning services",
  "Clergyman service",
  "Clinical research",
  "Clothes alteration",
  "Clothing boutique",
  "Clothing brand",
  "Clothing designer",
  "Clothing manufacturer",
  "Clothing store",
  "Coaching",
  "Coaching and consulting",
  "Coffee",
  "Coffee roasting",
  "Coffee shop",
  "Collectibles",
  "Collection agency",
  "Commercial and residential cleaning",
  "Commercial and residential painting",
  "Commercial art studio",
  "Commercial cleaning",
  "Commercial construction",
  "Commercial fishing",
  "Commercial real estate",
  "Commodity brokers",
  "Communications / public relations",
  "Community",
  "Computer repair",
  "Computer sales",
  "Concierge",
  "Concrete contractor",
  "Conglomerate",
  "Construction",
  "Construction consulting",
  "Construction management",
  "Construction services",
  "Consulting",
  "Consulting and training",
  "Consumer goods",
  "Content creator",
  "Contractor",
  "Convenience store",
  "Cosmetics",
  "Cosmetology",
  "Counseling",
  "Courier service",
  "CPR training",
  "Crafting",
  "Crafts",
  "Crafts store",
  "Crane operator",
  "Creative agency",
  "Creative consulting",
  "Creative services",
  "Credit card issuing",
  "Credit repair",
  "Cryptocurrency brokerage",
  "Cryptocurrency investing",
  "Cryptocurrency mining",
  "Customer service",
  "Cyber security consulting",
  "Dance instructor",
  "Dance studio",
  "Data analysis",
  "Data processing",
  "Data science",
  "Day spa",
  "Day trading",
  "Daycare",
  "Decorating business",
  "Delivery service",
  "Demolition",
  "Dental equipment & supplies manufacturing",
  "Dental services",
  "Dentistry",
  "Design",
  "Design consulting",
  "Designer",
  "Developer",
  "Dietary supplements",
  "Dietician",
  "Digital design agency",
  "Digital design consulting",
  "Digital marketing",
  "Digital marketing agency",
  "Digital media agency",
  "Digital products",
  "Dispatching services",
  "Dispensary",
  "Distribution",
  "DIY service",
  "DJ",
  "Doctors",
  "Dog boarding",
  "Dog breeding",
  "Dog grooming",
  "Dog training",
  "Dog walking",
  "Doula service",
  "Drain cleaning",
  "Drama school",
  "Driving school",
  "Drone photography",
  "Drone services - surveying",
  "Dropshipping",
  "Drug and alcohol recovery service",
  "Dry cleaning",
  "Drywall",
  "Dump truck",
  "Dumpster rental",
  "E-commerce",
  "Ebay business",
  "Ecommerce",
  "Education",
  "Education and training",
  "Education consulting",
  "Elderly care home",
  "Elderly care services",
  "Electrical",
  "Electrical contractor",
  "Electrical supplier",
  "Electrician",
  "Electronics",
  "Electronics store",
  "Embroidery",
  "Energy",
  "Energy consulting",
  "Engineering",
  "Engineering consulting",
  "Engineering firm",
  "Engraving",
  "Entertainment",
  "Entertainment services",
  "Environmental consulting",
  "Equestrian",
  "Equine",
  "Equipment leasing",
  "Equipment rental",
  "Equipment repair",
  "Estate sales",
  "Esthetician",
  "Etsy business",
  "Event planning",
  "Event production",
  "Event rentals",
  "Event venue services",
  "Events",
  "Excavation services",
  "Executive recruitment",
  "Expert witness service",
  "Exterior cleaning",
  "Eyelash extensions",
  "Fabrication",
  "Farming",
  "Fashion",
  "Fast food restaurant",
  "Fencing",
  "Film production",
  "Finance",
  "Financial consulting",
  "Financial services",
  "Fintech",
  "Fire protection",
  "Firearms manufacturing",
  "Firearms sales",
  "Firearms training",
  "Firewood",
  "Fish farming",
  "Fishery",
  "Fishing charters",
  "Fitness center",
  "Fitness coaching",
  "Fitness studio",
  "Flight training",
  "Flooring",
  "Florist",
  "Food catering",
  "Food consulting",
  "Food delivery courier",
  "Food delivery restaurant",
  "Food distribution",
  "Food manufacturing",
  "Food truck",
  "Food vending business",
  "Forestry",
  "Fragrance",
  "Franchising",
  "Freight",
  "Freight broker",
  "Freight transportation",
  "Funeral services",
  "Furniture design",
  "Furniture manufacturing",
  "Furniture sales",
  "Gadget store",
  "Gambling services",
  "Games designer",
  "Gaming service",
  "Garage door or gate repair service",
  "Garden landscaping",
  "Gardening",
  "Gas station",
  "General construction",
  "General contractor",
  "General freight",
  "General services",
  "Geology",
  "Gift store",
  "Gifts",
  "Golf accessories & apparel",
  "Golf carts",
  "Golf instruction",
  "Golf simulator",
  "Government contracting",
  "Graphic design",
  "Graphic design agency",
  "Green technology",
  "Grocery store",
  "Group home",
  "Gutter installation",
  "Gym",
  "Hair care services",
  "Hair extensions",
  "Hair products",
  "Hair removal",
  "Hair salon",
  "Hairdressing / hairstsyling",
  "Handmade products store",
  "Handyman service",
  "Haul freight",
  "Hauling",
  "Headhunting",
  "Healing",
  "Health and beauty",
  "Health and fitness coach",
  "Health and personal care retailers",
  "Health and wellness",
  "Health club",
  "Health coaching",
  "Health insurance",
  "Healthcare",
  "Healthcare consulting",
  "Hearing aid",
  "Hemp",
  "Holding company",
  "Holistic healing",
  "Home alarm",
  "Home bakery",
  "Home care",
  "Home cleaning",
  "Home decor",
  "Home goods",
  "Home health care",
  "Home improvement",
  "Home inspections",
  "Home maintenance and repair",
  "Home moving",
  "Home remodeling",
  "Home renovation",
  "Home rental",
  "Home security",
  "Home services",
  "Home staging",
  "Horse boarding",
  "Horse breeding or sales",
  "Horse racing",
  "Horse training",
  "Hospital",
  "Hospitality",
  "Hot shot trucking",
  "Hotel",
  "House cleaning",
  "House flipping",
  "House painting",
  "Household supply store",
  "Housekeeping",
  "Housing - construction",
  "Housing - real estate",
  "HR consulting",
  "Human resources consulting",
  "Human services",
  "Hunting",
  "HVAC",
  "Ice cream shop",
  "Ice cream truck",
  "Import / export goods service",
  "Industrial - construction",
  "Industrial - manufacturing",
  "Industrial - repair",
  "Influencer",
  "Information technology",
  "Information technology consulting",
  "Insurance adjusting",
  "Insurance agency",
  "Insurance brokerage",
  "Insurance services",
  "Interior decorating services",
  "Interior design",
  "Internet marketing",
  "Internet sales",
  "Investment advisors",
  "Investment club",
  "Investment management",
  "Investment property",
  "IT consulting",
  "IT services",
  "Janitorial service",
  "Jewelry",
  "Jewelry shop",
  "Juice bar",
  "Junk removal",
  "Labor",
  "Land clearing",
  "Land development",
  "Land management",
  "Land surveying",
  "Landscape design",
  "Landscaping",
  "Laser engraving",
  "Laundromat",
  "Laundry service",
  "Law practice",
  "Lawn care",
  "Lawncare",
  "Leasing business",
  "Legal services business",
  "Lending",
  "Life coaching",
  "Life insurance",
  "Lifestyle brand",
  "Lighting",
  "Limited service restaurant",
  "Liquor store",
  "Locksmith",
  "Lodging",
  "Logging business",
  "Logistics",
  "Lounge",
  "Low voltage",
  "Maintenance",
  "Makeup",
  "Management consulting",
  "Management services",
  "Manufacturing",
  "Manufacturing consulting",
  "Marijuana dispensary",
  "Marina services",
  "Marine - water transportation",
  "Maritime pilot",
  "Marketing",
  "Marketing consulting",
  "Marriage therapy",
  "Martial arts",
  "Masonry",
  "Massage",
  "Massage therapy",
  "Mechanic",
  "Mechanical",
  "Media",
  "Media agency",
  "Media management",
  "Media production",
  "Medical aesthetics",
  "Medical billing",
  "Medical center",
  "Medical consulting",
  "Medical device sales",
  "Medical equipment sales",
  "Medical practice",
  "Medical sales",
  "Medical services",
  "Medical spa",
  "Medical testing",
  "Medicine",
  "Mental health",
  "Mental health counseling",
  "Mental health therapy",
  "Merchandise",
  "Merchant services",
  "Metal fabrication",
  "Microblading",
  "Ministry",
  "Mobile bar",
  "Mobile bartending",
  "Mobile catering",
  "Mobile detailing",
  "Mobile food",
  "Mobile mechanic",
  "Mobile RV repair",
  "Model",
  "Modeling agency",
  "Mortgage brokerage",
  "Mortgage company",
  "Mortuary services",
  "Motion picture production",
  "Motorcycle repair",
  "Motorsports",
  "Moving company",
  "Multimedia",
  "Museum",
  "Music production",
  "Music publishing",
  "Music record label",
  "Music teacher",
  "Musical group",
  "Musician",
  "Nail salon",
  "Networking",
  "Nightclub",
  "Non emergency medical transportation",
  "Non-profit organization",
  "Notary",
  "Notary services",
  "Nursing home",
  "Nursing service",
  "Nutrition consulting",
  "Nutritionist",
  "Occupational therapy",
  "Office cleaning",
  "Oil and gas consulting",
  "Oil and gas operations",
  "Online boutique",
  "Online education services",
  "Online marketing",
  "Online marketplace",
  "Online retail store",
  "Online sales",
  "Online tech business",
  "Opticians",
  "Optometrist service",
  "Organizing",
  "Outdoor recreation",
  "Outdoor services",
  "Outdoors",
  "Outpatient service",
  "Own real estate",
  "Packaging and labeling services",
  "Packaging manufacturing",
  "Painting",
  "Painting and decorating",
  "Painting contractor",
  "Paralegal service",
  "Parent company",
  "Parking lots and garages",
  "Party planning",
  "Party rental",
  "Payment collections agency",
  "Payroll service",
  "Performing arts",
  "Permanent jewelry",
  "Permanent makeup",
  "Personal banking",
  "Personal care services",
  "Personal chef",
  "Personal coaching business",
  "Personal development",
  "Personal finance",
  "Personal services",
  "Personal training",
  "Pest control",
  "Pet boarding",
  "Pet care",
  "Pet daycare",
  "Pet food",
  "Pet grooming",
  "Pet products",
  "Pet services",
  "Pet sitting",
  "Pet spa",
  "Pet store",
  "Pet supplies",
  "Pharmaceutical",
  "Pharmaceutical consulting",
  "Pharmacy",
  "Phone store",
  "Photo booth",
  "Photographic art",
  "Photography",
  "Photography and videography",
  "Physical therapy",
  "Physician",
  "Physiotherapy",
  "Pilates studio",
  "Pilot services",
  "Plant nursery",
  "Plumbing",
  "Podcast",
  "Podiatrist service",
  "Pool services",
  "Powder coating",
  "Power washing",
  "Press / publishing",
  "Pressure washing",
  "Printing company",
  "Private equity",
  "Private investigator",
  "Procurement consulting",
  "Product development and design",
  "Production",
  "Production company",
  "Professional organizing",
  "Professional services",
  "Project management",
  "Property investment",
  "Property maintenance and preservation",
  "Property management",
  "Property rental",
  "Psychiatrist",
  "Psychologist",
  "Psychotherapy",
  "Public relations consulting",
  "Publishing",
  "Ranch",
  "Real estate",
  "Real estate agent",
  "Real estate appraisers",
  "Real estate broker",
  "Real estate consulting",
  "Real estate development",
  "Real estate holding company",
  "Real estate investing",
  "Real estate management",
  "Real estate rental",
  "Real estate services",
  "Record label",
  "Recording studio",
  "Recreation",
  "Recruitment agency",
  "Recycling services",
  "Remediation services",
  "Remodeling",
  "Renewable energy",
  "Renovation",
  "Rental and leasing services",
  "Rental property",
  "Repairs",
  "Research",
  "Reseller",
  "Residential cleaning",
  "Residential construction",
  "Restaurant",
  "Restaurant bar",
  "Restoration contractor",
  "Retail sales",
  "Ride share",
  "Roadside assistance",
  "Roofing",
  "RV park",
  "SaaS",
  "Safety",
  "Safety consulting",
  "Sales and marketing",
  "Sales consulting",
  "Sales financing",
  "Salon",
  "Sanitation",
  "Scientific research",
  "Screen printing",
  "Securities brokerage",
  "Security consulting",
  "Security services",
  "Self storage",
  "Sell clothing",
  "Sell merchandise",
  "Sell pet treats",
  "Sell products",
  "SEO",
  "Septic",
  "Sewing and alteration",
  "Shellfish farming",
  "Shipping",
  "Short term rentals",
  "Skin care products",
  "Skin care services",
  "Small engine repair",
  "Smoke shop",
  "Snow removal",
  "Soap",
  "Sober living",
  "Social club",
  "Social media",
  "Social media marketing",
  "Social services",
  "Social work",
  "Soft drink manufacturing",
  "Software",
  "Software consulting",
  "Software development",
  "Solar business",
  "Solar consulting",
  "Sound engineering",
  "Spa",
  "Speciality store",
  "Speech and language pathology",
  "Speech therapy",
  "Sporting goods",
  "Sports cards",
  "Sports club",
  "Sports entertainment",
  "Sports instruction",
  "Sports league",
  "Sports management consulting",
  "Sports media",
  "Sports promotion",
  "Sports team",
  "Sports trainer",
  "Spray tanning",
  "Staffing service",
  "Stationery",
  "Stock trading",
  "Storage",
  "Supplements",
  "Tailoring",
  "Takeout restaurant",
  "Talent agency",
  "Tanning salon",
  "Tattoo and body piercing salon",
  "Tattoo artist",
  "Tattoo salon",
  "Tax preparation",
  "Taxi service",
  "Taxidermy business",
  "Teaching",
  "Tech business",
  "Tech store",
  "Technology consulting",
  "Teeth whitening services",
  "Telecommunications",
  "Theme park",
  "Therapist",
  "Tobacco",
  "Tool sales",
  "Tourism services",
  "Towing",
  "Toys",
  "Trading",
  "Training",
  "Training and consulting",
  "Transport services",
  "Transportation",
  "Trash removal",
  "Travel advisor",
  "Travel agency",
  "Travel tours",
  "Tree services",
  "Tree surgery",
  "Trucking",
  "Trucking company",
  "Trust administration",
  "Tutoring",
  "Used car sales",
  "Utilities",
  "Vacation rentals",
  "Vehicle dealership",
  "Vending machine business",
  "Venture capital",
  "Venue hire services",
  "Veterinary medicine",
  "Video game development",
  "Video production",
  "Videography",
  "Virtual assistant",
  "Virtual call center",
  "Warehousing",
  "Waste management",
  "Waste removal",
  "Water",
  "Water treatment",
  "Waxing studio",
  "Wealth management",
  "Web design",
  "Web design consulting",
  "Website development",
  "Wedding photography",
  "Wedding planning consulting",
  "Wedding rental",
  "Welding",
  "Welding and fabrication",
  "Wellness and health",
  "Wellness and health center",
  "Wholesale",
  "Window cleaning",
  "Window tinting",
  "Wine bar",
  "Winery",
  "Woodwork",
  "Writing and editing service",
  "Yacht charter",
  "Yacht sales",
  "Yoga",
  "Yoga instruction",
  "Yoga studio",
  "Youth care business",
  "Youth sports",
  "YouTube",
];
