/**
 * Generate type-safe `as const` ABIs from Foundry artifacts in ../out.
 * Run: npm run gen:abis  (re-run after any contract change + `forge build`).
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "..", "..", "out");
const DEST = resolve(HERE, "..", "src", "abis", "generated.ts");

// exportName -> artifact path under out/<Sol>/<Json>
const TARGETS: Record<string, string> = {
  legalManagerFactoryAbi: "LegalManagerFactory.sol/LegalManagerFactory.json",
  legalManagerAbi: "LegalManager.sol/LegalManager.json",
  agentTreasuryAbi: "AgentTreasury.sol/AgentTreasury.json",
  iIdentityRegistryAbi: "IIdentityRegistry.sol/IIdentityRegistry.json",
  // Test-only doubles (used by anvil integration tests):
  mockIdentityRegistryAbi: "MockIdentityRegistry.sol/MockIdentityRegistry.json",
  mockUsdcAbi: "MockUSDC.sol/MockUSDC.json",
  iErc8183JobAbi: "IERC8183Job.sol/IERC8183Job.json",
  mockErc8183JobAbi: "MockERC8183Job.sol/MockERC8183Job.json",
  reputationRegistryAbi: "IERC8183Reputation.sol/IERC8183Reputation.json",
  mockReputationRegistryAbi: "MockReputationRegistry.sol/MockReputationRegistry.json",
};

function loadAbi(rel: string): unknown {
  const json = JSON.parse(readFileSync(resolve(OUT, rel), "utf8"));
  if (!Array.isArray(json.abi)) throw new Error(`no abi in ${rel}`);
  return json.abi;
}

let body = "// GENERATED by scripts/gen-abis.mts — do not edit by hand.\n";
body += "// Re-run `npm run gen:abis` after `forge build`.\n\n";
for (const [name, rel] of Object.entries(TARGETS)) {
  const abi = loadAbi(rel);
  body += `export const ${name} = ${JSON.stringify(abi)} as const;\n\n`;
}

mkdirSync(dirname(DEST), { recursive: true });
writeFileSync(DEST, body);
console.log(`wrote ${DEST} (${Object.keys(TARGETS).length} ABIs)`);
